config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :stylists #handles all things for CRUD
  get 'home/about'
  root 'home#index'
  #get 'upload_gallery_image#upload'

  # get is a method, and the arguments are a string and hash
  #get '/upload', controller: 'upload_gallery_image', action: 'upload'

  # can also say something like:
  #get 'upload_gallery_image#upload'
  get '/upload' => 'upload_gallery_image#upload'

  #get 'upload_gallery_image#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stylist.rb
class Stylist < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :stylists
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/stylists_controller.rb
class StylistsController < ApplicationController
  before_action :set_stylist, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /stylists or /stylists.json
  def index
    @stylists = Stylist.all
  end

  # GET /stylists/1 or /stylists/1.json
  def show
  end

  # GET /stylists/new
  def new
    #@stylist = stylist.new
    @stylist = current_user.stylists.build
  end

  # GET /stylists/1/edit
  def edit
  end

  # POST /stylists or /stylists.json
  def create
    #@stylist = stylist.new(stylist_params)
    @stylist = current_user.stylists.build(stylist_params)

    respond_to do |format|
      if @stylist.save
        format.html { redirect_to @stylist, notice: "stylist was successfully created." }
        format.json { render :show, status: :created, location: @stylist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stylist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stylists/1 or /stylists/1.json
  def update
    respond_to do |format|
      if @stylist.update(stylist_params)
        format.html { redirect_to @stylist, notice: "stylist was successfully updated." }
        format.json { render :show, status: :ok, location: @stylist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stylist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stylists/1 or /stylists/1.json
  def destroy
    @stylist.destroy
    respond_to do |format|
      format.html { redirect_to stylists_url, notice: "stylist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @stylist = current_user.stylists.find_by(id: params[:id])
    redirect_to stylists_path, notice: "not authorized to edit this stylist" if @stylist.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stylist
      @stylist = Stylist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stylist_params
      params.require(:stylist).permit(:first_name, :last_name, :email, :phone, :instagram, :user_id)
    end
end

app/controllers/upload_gallery_image_controller.rb
class UploadGalleryImageController < ApplicationController
  
  def upload
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stylists_helper.rb
module StylistsHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :instagram %>
    <%= form.text_field :instagram %>
  </div>

  <div class="field">
    <%= form.number_field :user_id, id: :friend_user_id ,value:current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Balayage App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Gallery', home_about_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Stylists', stylists_path, class:"nav-link"%>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
          <%= link_to 'New Stylist', new_stylist_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit profile', edit_user_registration_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign-out', destroy_user_session_path, method: :delete, class:"nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
          <%= link_to 'Sign-up', new_user_registration_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign-in', new_user_session_path, class:"nav-link"%>
        </li>
        <% end %>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<%= stylesheet_link_tag 'about' %>
<%= javascript_pack_tag 'gallery' %>

<%= link_to 'Upload Image', upload_path, class:'btn btn-secondary'%>

<section class="gallery min-vh-100">
	<div class="container-lg">

		<div class="row gy-4 row-cols-1 row-cols-sm-2 row-cols-md-3">
			
			<div class="col">
				<%= image_tag "brownToBlonde/one.jpg", class: "gallery-item" %> 
				<p>very nice</p>
			</div>
			<div class="col">
				<%= image_tag "brownToBlonde/two.jpg", class: "gallery-item"  %> 
				<p>hello</p>
			</div>
			<div class="col">
				<%= image_tag "brownToBlonde/three.jpg", class: "gallery-item"  %> 
			</div>
			<div class="col">
				<%= image_tag "brownToBlonde/four.jpg", class: "gallery-item"  %> 
			</div>
			<div class="col">
				<%= image_tag "brownToBlonde/five.jpg", class: "gallery-item"  %> 
			</div>
			<div class="col">
				<%= image_tag "brownToBlonde/six.jpg", class: "gallery-item"  %> 
			</div>
			<div class="col">
				<%= image_tag "brownToBlonde/seven.jpg", class: "gallery-item"  %> 
			</div>
			<div class="col">
				<%= image_tag "brownToBlonde/eight.jpg", class: "gallery-item"  %> 
			</div>

		</div>

	</div>

</section>


<!-- Modal -->
<div class="modal fade" id="gallery-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <!-- <h5 class="modal-title" id="exampleModalLabel">Modal title</h5> -->
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      	<%= image_tag "brownToBlonde/seven.jpg", class:"modal-img" %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1>Balayage</h1>
<h2>Brown --> Blonde</h2>
Search for your new look, find a hair salon, and book an appointment!

Send messages to your stylist (hopefully send them the style you want as a picture!)

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>stylists App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header'%>
    <div class = 'container'>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
        <br/>      
        <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/stylists/_form.html.erb
<%= form_with(model: stylist) do |form| %>
  <% if stylist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stylist.errors.count, "error") %> prohibited this stylist from being saved:</h2>

      <ul>
        <% stylist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :instagram %>
    <%= form.text_field :instagram %>
  </div>

  <div class="field">
    <%= form.number_field :user_id, id: :stylist_user_id ,value:current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stylists/edit.html.erb
<h1>Editing stylist</h1>

<%= render 'form', stylist: @stylist %>

<%= link_to 'Show', @stylist %> |
<%= link_to 'Back', stylists_path %>

app/views/stylists/index.html.erb
<table class="table table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Instagram</th>
      <th>User id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stylists.each do |stylist| %>
      <tr>
        <td><%= stylist.first_name %></td>
        <td><%= stylist.last_name %></td>
        <td><%= stylist.email %></td>
        <td><%= stylist.phone %></td>
        <td><%= stylist.instagram %></td>
        <td><%= stylist.user_id %></td>
        <td><%= link_to 'Profile', stylist %></td>
        <td><%= link_to 'Edit', edit_stylist_path(stylist) %></td>
        <td><%= link_to 'Destroy', stylist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stylist', new_stylist_path, class:'btn btn-secondary'%>

app/views/stylists/new.html.erb
<h1>Add New stylist</h1>

<%= render 'form', stylist: @stylist %>

<%= link_to 'Back', stylists_path %>

app/views/stylists/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @stylist.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @stylist.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @stylist.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @stylist.phone %>
</p>

<p>
  <strong>Instagram:</strong>
  <%= @stylist.instagram %>
</p>

<%= link_to 'Edit', edit_stylist_path(@stylist), class:'btn btn-secondary'%> 
<%= link_to 'Back', stylists_path, class:'btn btn-secondary' %>

app/views/upload_gallery_image/upload.html.erb
<h1> Upload your work here </h1>